import { Inter } from 'next/font/google';
import style from './globals.css';
import Formulario from './components/form';
import React from 'react';
import Footer from './components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className='wrapper'>
        {children}
        <br />
        <Footer />
        </div>
      </body>
    </html>
  );
}

